version: 2.1

executors:
  metal:
    machine:
      image: ubuntu-1604:201903-01

workflows:
  test_build:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - boolafish/base_upon_revamp_branch

jobs:
  publish:
    executor: metal
    steps:
      - checkout
      - run:
          name: publish to GCP container registry
          command: |
            GIT_COMMIT_SHA=$(git rev-parse HEAD)
            TEST_RUNNER_TAG=gcr.io/omisego-development/omg-js-testrunner:dev-boolafish-testrunner-$GIT_COMMIT_SHA

            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud -q auth configure-docker

            docker build -t testrunner .
            docker tag testrunner $TEST_RUNNER_TAG
            docker push $TEST_RUNNER_TAG

            # add tag for omg-js sha
            gcloud container images add-tag \
            $TEST_RUNNER_TAG \
            gcr.io/omisego-development/omg-js-testrunner:dev-boolafish-omg-js-$(cat ./OMG_JS_SHA)
