version: 2.1

executors:
  metal:
    machine:
      image: ubuntu-1604:201903-01

workflows:
  test_build:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master

jobs:
  publish:
    executor: metal
    steps:
      - checkout
      - run:
          name: publish to GCP container registry
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud -q auth configure-docker
            docker build -t testrunner .
            docker tag testrunner gcr.io/omisego-development/omg-js-testrunner
            docker push gcr.io/omisego-development/omg-js-testrunner
